"""adding car table

Revision ID: 290607721bde
Revises: 1bb18b4fcba4
Create Date: 2021-06-23 22:29:41.512045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290607721bde'
down_revision = '1bb18b4fcba4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('make', sa.String(length=150), nullable=True),
    sa.Column('model', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
